Lauren finding words
lsunn/Strands pull request #2
Opened 2024-06-28 01:26 UTC by lsunn

2024-07-02 01:10 UTC, puzonevan requested changes

2024-07-02 01:10 UTC, puzonevan commented on src/Board.js
> +        }
boop indentation pls

2024-07-02 01:10 UTC, puzonevan commented on src/Board.js
> +                        onMouseUp={() => handleMouseUp(rowIndex, colIndex)}/>
I see what's happening here. Usually I wouldn't mind the logic living here. Logic being handleMouseDown, handleMouseEnter, etc. Buttttt, it shouldn't live here. That logic belongs in the `<Cell />` component

```suggestion
                        cell={cell}
                        position={[rowIndex, colIndex]}
                        setIsDragging={setIsDragging}
                        setChosenLetters={setChosenLetters}
                        setSelectedCells={setSelectedCells}
                        ...
```

There is argument to be made that is more props, but doing that allows the logic `handleMouseDown` etc. to live in the `<Cell />` component overall reducing the bloat on this `<Board />` component.

Remember this board component is the most high level component. Functional Logic that should live in a children should live in the children. The high level component should contain high level logic like the state and `checkWord` can actually live in this component still

2024-07-02 19:51 UTC, puzonevan commented
Nice work on this. Let's establish some more process for PR's 

1. Title - no need to put your name. Just make sure it's meaningful "Implement finding words"
2. Set up a description template . Let's start with 3 sections `Overview - What does this ticket accomplish` `Test Url - deploy link for me to look at` `Test Scenarios - step by step scenarios of things to test`

2024-07-03 08:44 UTC, lsunn commented on package.json
> +    "nspell": "^2.1.5",
nope not used yet but I think I might use a different library instead

2024-07-12 00:40 UTC, merged